"""
Data management endpoints — let users view, edit, and delete their
per-user runtime files (user_plan.md, RULES.md, data/holdings.json).

These files are gitignored — they're per-user, generated by Onboarding,
modified by Strategist/Risk/Execution. The Profile UI uses these
endpoints to render the data and let users manage it directly.
"""

from __future__ import annotations

import asyncio
import io
import json
import re
from pathlib import Path
from typing import Any

from fastapi import APIRouter, HTTPException, UploadFile, File
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

router = APIRouter(prefix="/api/data", tags=["data"])

# Resolved by main.py at import time
AGENT_DIR = Path(__file__).resolve().parent.parent


# ─────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────


def user_plan_path() -> Path:
    return AGENT_DIR / "memory" / "user_plan.md"


def rules_path() -> Path:
    return AGENT_DIR / "RULES.md"


def holdings_path() -> Path:
    return AGENT_DIR / "data" / "holdings.json"


def parse_user_plan(md: str) -> dict[str, Any]:
    """Extract structured fields from user_plan.md so the UI can render
    a clean form. Best-effort regex — won't match all variants."""
    out: dict[str, Any] = {}

    def grab(pattern: str, group: int = 1) -> str | None:
        m = re.search(pattern, md, re.MULTILINE | re.IGNORECASE)
        return m.group(group).strip() if m else None

    out["goalType"] = grab(r"^-\s*Type:\s*(.+)$") or grab(r"Goal[:\s]+(.+)")
    out["targetAmount"] = grab(r"Target Amount:\s*₹?([\d,]+)")
    out["targetDate"] = grab(r"Target Date:\s*(.+)")
    out["timeHorizon"] = grab(r"Time Horizon:\s*(.+)")
    out["portfolioValue"] = grab(r"Portfolio Value:\s*₹?([\d,]+)")
    out["monthlyIncome"] = grab(r"Monthly Income:\s*₹?([\d,]+)")
    out["netInvestable"] = grab(r"Net Monthly Investable:\s*₹?([\d,]+)")
    out["riskTolerance"] = grab(r"Tolerance:\s*([A-Za-z]+)")

    # Constraints — pull as a list
    constraints_section = re.search(
        r"Hard Constraints:?\s*\n((?:\s*-\s*.+\n?)+)",
        md,
        re.IGNORECASE,
    )
    if constraints_section:
        out["hardConstraints"] = [
            line.strip().lstrip("-").strip()
            for line in constraints_section.group(1).splitlines()
            if line.strip().startswith("-")
        ]
    return out


# ─────────────────────────────────────────────────────────────────────────
# Status — what files exist?
# ─────────────────────────────────────────────────────────────────────────


@router.get("/files")
def get_file_status():
    """Return existence + size of each per-user runtime file."""

    def stat_or_none(p: Path) -> dict | None:
        if not p.exists():
            return None
        return {
            "size": p.stat().st_size,
            "modified": p.stat().st_mtime,
        }

    return {
        "user_plan": stat_or_none(user_plan_path()),
        "rules": stat_or_none(rules_path()),
        "holdings": stat_or_none(holdings_path()),
    }


# ─────────────────────────────────────────────────────────────────────────
# user_plan.md — get, update, delete
# ─────────────────────────────────────────────────────────────────────────


@router.get("/user_plan")
def get_user_plan():
    p = user_plan_path()
    if not p.exists():
        raise HTTPException(404, "user_plan.md not found — run onboarding first")
    raw = p.read_text(encoding="utf-8")
    return {"raw": raw, "parsed": parse_user_plan(raw)}


class UserPlanUpdate(BaseModel):
    raw: str


@router.put("/user_plan")
def put_user_plan(body: UserPlanUpdate):
    if not body.raw or len(body.raw) < 20:
        raise HTTPException(400, "user_plan content seems too short")
    p = user_plan_path()
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(body.raw, encoding="utf-8")
    return {"ok": True, "size": len(body.raw)}


@router.delete("/user_plan")
def delete_user_plan():
    """
    Removes user_plan.md AND RULES.md (RULES is derived from user_plan,
    keeping it after deletion would leave the agent in an inconsistent state).
    User must re-run Onboarding after this.
    """
    deleted: list[str] = []
    for p in (user_plan_path(), rules_path()):
        if p.exists():
            p.unlink()
            deleted.append(p.name)
    return {"ok": True, "deleted": deleted}


# ─────────────────────────────────────────────────────────────────────────
# RULES.md — get only (regenerated via onboarding/update, not directly edited)
# ─────────────────────────────────────────────────────────────────────────


@router.get("/rules")
def get_rules():
    p = rules_path()
    if not p.exists():
        raise HTTPException(404, "RULES.md not found")
    return {"raw": p.read_text(encoding="utf-8")}


# ─────────────────────────────────────────────────────────────────────────
# holdings.json — get, upload (csv/excel/json), delete
# ─────────────────────────────────────────────────────────────────────────


@router.get("/holdings")
def get_holdings():
    p = holdings_path()
    if not p.exists():
        raise HTTPException(404, "data/holdings.json not found — upload first")
    try:
        return {"holdings": json.loads(p.read_text(encoding="utf-8"))}
    except json.JSONDecodeError as e:
        raise HTTPException(500, f"holdings.json is malformed: {e}")


@router.delete("/holdings")
def delete_holdings():
    p = holdings_path()
    if p.exists():
        p.unlink()
        return {"ok": True, "deleted": "data/holdings.json"}
    return {"ok": True, "deleted": None}


def _normalize_columns(headers: list[str]) -> dict[str, int]:
    """Map flexible column names to canonical indices."""
    aliases = {
        "symbol": ["symbol", "ticker", "stock", "code", "scrip"],
        "qty": ["qty", "quantity", "shares", "units", "qty_held"],
        "avg_price": ["avg_price", "avg price", "average price", "buy price", "avg", "avgprice", "cost"],
    }
    norm = [h.strip().lower() for h in headers]
    mapping: dict[str, int] = {}
    for canonical, options in aliases.items():
        for opt in options:
            if opt in norm:
                mapping[canonical] = norm.index(opt)
                break
    missing = [k for k in aliases if k not in mapping]
    if missing:
        raise HTTPException(
            400,
            f"Missing required columns: {missing}. Got headers: {headers}. "
            f"Expected columns matching: symbol, qty, avg_price (flexible names).",
        )
    return mapping


def parse_csv_rows(rows: list[list[str]]) -> list[dict]:
    if not rows:
        raise HTTPException(400, "Uploaded file has no rows")
    headers = rows[0]
    mapping = _normalize_columns(headers)
    parsed: list[dict] = []
    for i, row in enumerate(rows[1:], start=2):
        if not any(cell.strip() for cell in row):
            continue  # skip blank rows
        try:
            sym = row[mapping["symbol"]].strip().upper()
            qty = float(row[mapping["qty"]].replace(",", "").strip())
            avg = float(row[mapping["avg_price"]].replace(",", "").strip())
            if not sym or qty <= 0 or avg <= 0:
                continue
            parsed.append({"symbol": sym, "qty": qty, "avg_price": avg})
        except (IndexError, ValueError) as e:
            raise HTTPException(
                400, f"Row {i} parse error: {e}. Row content: {row}"
            )
    if not parsed:
        raise HTTPException(400, "No valid holdings rows found after parsing")
    return parsed


@router.post("/holdings/upload")
async def upload_holdings(file: UploadFile = File(...)):
    """
    Accepts CSV, XLSX, or JSON. Parses into the canonical holdings format
    and writes to data/holdings.json.

    Expected columns (flexible naming):
      - symbol / ticker / stock
      - qty / quantity / shares
      - avg_price / avg price / cost

    JSON must already be an array of {symbol, qty, avg_price} objects.

    Size limit: 10 MB. Larger files are rejected to prevent OOM.
    """
    MAX_UPLOAD_BYTES = 10 * 1024 * 1024  # 10 MB
    fname = (file.filename or "").lower()
    content = await file.read()
    if len(content) > MAX_UPLOAD_BYTES:
        raise HTTPException(
            413,
            f"File too large ({len(content) / 1024 / 1024:.1f} MB). "
            f"Limit is {MAX_UPLOAD_BYTES // 1024 // 1024} MB.",
        )

    if fname.endswith(".json"):
        try:
            parsed = json.loads(content)
        except json.JSONDecodeError as e:
            raise HTTPException(400, f"Invalid JSON: {e}")
        if not isinstance(parsed, list):
            raise HTTPException(400, "JSON must be an array of holdings")
        # Validate shape
        cleaned: list[dict] = []
        for i, h in enumerate(parsed):
            if not isinstance(h, dict):
                raise HTTPException(400, f"Row {i} is not an object")
            try:
                cleaned.append(
                    {
                        "symbol": str(h["symbol"]).strip().upper(),
                        "qty": float(h["qty"]),
                        "avg_price": float(h["avg_price"]),
                    }
                )
            except (KeyError, ValueError) as e:
                raise HTTPException(
                    400, f"Row {i} missing field or invalid value: {e}"
                )
        holdings = cleaned
    elif fname.endswith(".csv"):
        import csv as csv_mod

        rows = list(
            csv_mod.reader(io.StringIO(content.decode("utf-8", errors="replace")))
        )
        holdings = parse_csv_rows(rows)
    elif fname.endswith((".xlsx", ".xls")):
        try:
            import openpyxl  # noqa: F401
        except ImportError:
            raise HTTPException(500, "openpyxl not installed on server")
        from openpyxl import load_workbook

        wb = load_workbook(io.BytesIO(content), data_only=True)
        ws = wb.active
        rows = [
            [str(c) if c is not None else "" for c in row]
            for row in ws.iter_rows(values_only=True)
        ]
        holdings = parse_csv_rows(rows)
    else:
        raise HTTPException(
            400,
            f"Unsupported file type: {fname}. Accepts .csv, .xlsx, .xls, .json",
        )

    out = holdings_path()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(holdings, indent=2), encoding="utf-8")
    return {"ok": True, "count": len(holdings), "holdings": holdings}


# ─────────────────────────────────────────────────────────────────────────
# Update-via-chat — invoke gitclaw with a natural-language change request
# ─────────────────────────────────────────────────────────────────────────


class ChatUpdateRequest(BaseModel):
    target: str  # "user_plan" | "rules" | "holdings"
    instruction: str  # e.g. "Change my risk tolerance to high"


@router.post("/update-via-chat")
async def update_via_chat(req: ChatUpdateRequest):
    """
    Stream a gitclaw invocation that interprets the user's natural-language
    instruction and modifies the target file. The agent is given:
      - the current file content
      - the user's instruction
      - explicit constraints (don't touch unrelated fields)

    Returns NDJSON stream of gitclaw events, same shape as /api/run.
    """
    target = req.target
    if target == "user_plan":
        path = user_plan_path()
        file_label = "memory/user_plan.md"
    elif target == "rules":
        path = rules_path()
        file_label = "RULES.md"
    elif target == "holdings":
        path = holdings_path()
        file_label = "data/holdings.json"
    else:
        raise HTTPException(400, f"Invalid target: {target}")

    if not path.exists():
        raise HTTPException(404, f"{file_label} does not exist")

    current = path.read_text(encoding="utf-8")
    instruction = req.instruction.replace('"', "'")  # keep prompt unbroken

    prompt = f"""The user wants to update their {file_label} file. Here is the CURRENT content:

```
{current}
```

The user's instruction: "{instruction}"

Modify ONLY the fields the user explicitly asked about. Do not change anything else.
Write the updated content back to {file_label} using your write tool.
After writing, confirm with one sentence describing what changed."""

    async def stream():
        def sse_event(obj: dict) -> bytes:
            return (json.dumps(obj) + "\n").encode("utf-8")

        yield sse_event({"type": "session_start", "target": file_label})
        try:
            process = await asyncio.create_subprocess_exec(
                "gitclaw",
                "--dir",
                str(AGENT_DIR),
                "--prompt",
                prompt,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.STDOUT,
            )
            assert process.stdout is not None
            async for raw in process.stdout:
                text = raw.decode("utf-8", errors="replace").rstrip("\n")
                if not text:
                    continue
                event_type = "output"
                if text.lstrip().startswith("▶"):
                    event_type = "tool_use"
                elif text.lstrip().startswith("✗"):
                    event_type = "error_line"
                yield sse_event({"type": event_type, "text": text})
            rc = await process.wait()
            yield sse_event({"type": "session_end", "return_code": rc})
        except FileNotFoundError:
            yield sse_event(
                {"type": "error", "message": "gitclaw CLI not found in PATH"}
            )
        except Exception as e:  # noqa: BLE001
            yield sse_event({"type": "error", "message": str(e)})

    return StreamingResponse(
        stream(),
        media_type="application/x-ndjson",
        headers={
            "Cache-Control": "no-cache, no-transform",
            "X-Accel-Buffering": "no",
        },
    )
